---
title: "Max_Jinshi_meeting"
author: "Jinshi and Max"
date: "7/6/2020"
output: html_document
---

```{r package, include = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(readxl)
library(styler)
library(ggplot2)
theme_set(theme_bw())
library(cowplot)
library(tidyr)
library(dplyr)
library(data.table)
library(lubridate)
library(kableExtra)
library(knitr)
library(ggpubr)
library(ggmap)
library(maps)
library(mapdata)
library(RColorBrewer)
# install.packages("patchwork")
library(patchwork)
# not in function
'%!in%' <- function(x,y)!('%in%'(x,y))
```


```{r data processing, echo = FALSE}
srdbv5 <- read.csv(here::here("Data", "srdb-data.csv"))
IGBP_Koppen_MODIS <- read.csv(here::here("Data", "IGBP_Koppen_MODIS.csv"))

# using mutate and case_when regroup climate
IGBP_Koppen_MODIS %>% 
  mutate(MiddleClimate = case_when(
    ClimateTypes %in% c("Af", "Am", "As", "Aw") ~ "A",
    ClimateTypes %in% c("BSh", "BSk", "BWh", "BWk") ~ "B",
    ClimateTypes %in% c("Cfa", "Cfb", "Cfc") ~ "Cf",
    ClimateTypes %in% c("Csa", "Csb", "Csc") ~ "Cs",
    ClimateTypes %in% c("Cwa", "Cwb", "Cwc") ~ "Cw",
    ClimateTypes %in% c("Dfa", "Dfb", "Dfc", "Dfd") ~ "Df",
    ClimateTypes %in% c("Dsa", "Dsb", "Dsc", "Dwa", "Dwb", "Dwc", "Dwd") ~ "Dsw",
    ClimateTypes %in% c("EF", "ET") ~ "E",
    TRUE ~ "Other")) ->
  IGBP_Koppen_MODIS
```


```{r plot annual Rs by measurement method}
# Find out number of observations for each measurement method
srdbv5 %>% 
  select(Rs_annual, Meas_method) %>% 
  na.omit() %>% 
  filter(Rs_annual < 2000) %>% 
  count(Meas_method)

# plot your figure  
srdbv5 %>% 
  select(Rs_annual, Meas_method) %>% 
  na.omit() %>% 
  filter(Rs_annual < 2000) %>% 
  filter(Meas_method %!in% c("", "Unknown", "Isotope", "Other")) %>% #filter those out (not too much data)
  # count(Meas_method)
  ggplot(aes(Meas_method, Rs_annual, fill = Meas_method)) +
  geom_violin(draw_quantiles = c(.25, 0.5, .75)) +
  theme(legend.title = element_blank(),
        # axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 30, vjust = 0.5)) +
  scale_x_discrete(labels = c("AA(614)", "EC(12)", "Equation(13)", "GC(642)", "Gradient(39)", "IRGA(4134)")) +
  scale_fill_discrete(breaks=c("Alkali absorption", "EC", "Equation", "Gas chromatography", "Gradient", "IRGA"),
                        labels=c("AA", "EC", "Equation", "GC", "Gradient", "IRGA")) +
  labs(title = "Distribution of Annual Rs by Measurement method", 
       y = expression(Annual~R[S]~(g~C~m^{-2}~yr^{-1})), 
       x = "Measurement Method")
```


```{r plot RC by different partitioning method}
srdbv5 %>% 
  select(RC_annual, Partition_method, Manipulation) %>% 
  na.omit() %>% 
  filter(RC_annual <= 1 & RC_annual >= 0) %>% 
  filter(Manipulation == "None") %>% # this will filter out those measurements with treatment
  count(Partition_method)

# plot your figure
srdbv5 %>% 
  select(RC_annual, Partition_method, Manipulation) %>% 
  na.omit() %>% 
  filter(RC_annual <= 1 & RC_annual >= 0) %>% 
  filter(Partition_method %!in% c("", "Other", "Girdling", "TBCA")) %>% #filter those out (not too much data)
  ggplot(aes(Partition_method, RC_annual, fill = Partition_method)) +
  geom_violin(draw_quantiles = c(.25, 0.5, .75)) +
  theme(legend.title = element_blank(),
        # axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 30, vjust = .5)) +
  scale_x_discrete(labels = c("Comparion(54)", "Exclusion(387)", "Extraction(110)", "Isotope(17)", "Model(29)", "Subtraction(57)")) +
  labs(y = expression(Annual~R[root]~Contribution~to~R[S]),
       x = "Partitioning Method") -> plot1
```


```{r link Climate and vegetation}
# Need to update latitude and longitude
# Change Latitude and Longitude to 0.5*0.5 resolution
srdbv5 %>% 
  mutate(Latitude2 = round(Latitude*2)/2+0.25, Longitude2 = round(Longitude*2)/2+0.25) -> 
  srdbv5

srdbv5 %>% 
  select(Latitude, Latitude2, Longitude, Longitude2)

# Get Ecosystem class, MAT and MAP for srdb data
left_join(srdbv5, IGBP_Koppen_MODIS, by=c("Latitude2" = "Latitude", "Longitude2" = "Longitude")) -> 
  srdbv5
```

``` {r RCbyClimateAndVeg}
srdbv5 %>% 
  filter(!is.na(MiddleClimate)) %>%
  ggplot(aes(x = MiddleClimate, y = RC_annual, fill = MiddleClimate)) +
  geom_violin(draw_quantiles = c(.25, .5, .75)) +
  theme(legend.title = element_blank()) +
  theme_minimal() -> plot2

srdbv5 %>% 
  filter(!is.na(Ecosystem)) %>% 
  filter(!is.na(RC_annual)) %>%
  ggplot(aes(x = Ecosystem, y = RC_annual, fill = Ecosystem)) +
  geom_violin(draw_quantiles = c(.25, .5, .75)) +
  theme_minimal() +
  theme(legend.title = element_blank(),
        # axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 30, vjust = .5)) -> plot3

srdbv5 %>% 
  filter(!is.na(Ecosystem_type)) %>% 
  filter(!is.na(RC_annual)) %>%
  filter(Ecosystem_type != "Orchard" & Ecosystem_type != "Urban") %>% # Filter out categories with not enough RC_annual data
  ggplot(aes(x = Ecosystem_type, y = RC_annual, fill = Ecosystem_type)) +
  geom_violin(draw_quantiles = c(.25, .5, .75)) +
  theme_minimal() +
  theme(legend.title = element_blank(),
        # axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 30, vjust = 0.5)) -> plot4
```

```{r 4In1Plot}
plot_grid(plot1, plot2, plot3, plot4)
```